// <auto-generated />
namespace DriverApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview3-19553-01")]
    public sealed partial class DriverTaskTableCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DriverTaskTableCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201911270657207_DriverTaskTableCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
